In [1]:
import numpy as np

In [6]:
a = np.array([1.34,2.9,3.8])
print(a)
print(a.dtype)
a2 = a.astype(int)
print(a2)

[1.34 2.9  3.8 ]
float64
[1 2 3]


In [11]:
b = np.array([[1,2,23], [34,56,84], [67,2,56]])
print(b)

d = np.linalg.det(b)
print(d)

e = np.eye(5)
print(e)


[[ 1  2 23]
 [34 56 84]
 [67  2 56]]
-74316.0
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
f = np.random.random((5))
print(f)

h = np.random.randn((5))
print(h)

g = (10*np.random.random((5)))
g2 = g.astype(int)
print(g2)

[0.46322441 0.33766204 0.79965534 0.30244625 0.46741492]
[-1.40911386 -0.14701748 -0.26152164 -1.57758679  0.55778011]
[6 6 0 8 1]


In [21]:
gnr = np.random.default_rng(0)
print(gnr)
i = gnr.random(10)
print(i)

Generator(PCG64)
[0.63696169 0.26978671 0.04097352 0.01652764 0.81327024 0.91275558
 0.60663578 0.72949656 0.54362499 0.93507242]


In [22]:
p = gnr.integers(10, size = (3,4))
print(p)

[[2 8 6 0]
 [3 8 5 0]
 [7 7 8 1]]
